// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: admin.proto

package admin_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WishlistAdmin_GenerateInviteCode_FullMethodName = "/admin.WishlistAdmin/GenerateInviteCode"
	WishlistAdmin_VistesImport_FullMethodName       = "/admin.WishlistAdmin/VistesImport"
)

// WishlistAdminClient is the client API for WishlistAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WishlistAdminClient interface {
	GenerateInviteCode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*IvniteCodeReply, error)
	VistesImport(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type wishlistAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewWishlistAdminClient(cc grpc.ClientConnInterface) WishlistAdminClient {
	return &wishlistAdminClient{cc}
}

func (c *wishlistAdminClient) GenerateInviteCode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*IvniteCodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IvniteCodeReply)
	err := c.cc.Invoke(ctx, WishlistAdmin_GenerateInviteCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wishlistAdminClient) VistesImport(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WishlistAdmin_VistesImport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WishlistAdminServer is the server API for WishlistAdmin service.
// All implementations must embed UnimplementedWishlistAdminServer
// for forward compatibility.
type WishlistAdminServer interface {
	GenerateInviteCode(context.Context, *emptypb.Empty) (*IvniteCodeReply, error)
	VistesImport(context.Context, *ImportRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedWishlistAdminServer()
}

// UnimplementedWishlistAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWishlistAdminServer struct{}

func (UnimplementedWishlistAdminServer) GenerateInviteCode(context.Context, *emptypb.Empty) (*IvniteCodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateInviteCode not implemented")
}
func (UnimplementedWishlistAdminServer) VistesImport(context.Context, *ImportRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VistesImport not implemented")
}
func (UnimplementedWishlistAdminServer) mustEmbedUnimplementedWishlistAdminServer() {}
func (UnimplementedWishlistAdminServer) testEmbeddedByValue()                       {}

// UnsafeWishlistAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WishlistAdminServer will
// result in compilation errors.
type UnsafeWishlistAdminServer interface {
	mustEmbedUnimplementedWishlistAdminServer()
}

func RegisterWishlistAdminServer(s grpc.ServiceRegistrar, srv WishlistAdminServer) {
	// If the following call pancis, it indicates UnimplementedWishlistAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WishlistAdmin_ServiceDesc, srv)
}

func _WishlistAdmin_GenerateInviteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistAdminServer).GenerateInviteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistAdmin_GenerateInviteCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistAdminServer).GenerateInviteCode(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WishlistAdmin_VistesImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WishlistAdminServer).VistesImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WishlistAdmin_VistesImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WishlistAdminServer).VistesImport(ctx, req.(*ImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WishlistAdmin_ServiceDesc is the grpc.ServiceDesc for WishlistAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WishlistAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.WishlistAdmin",
	HandlerType: (*WishlistAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateInviteCode",
			Handler:    _WishlistAdmin_GenerateInviteCode_Handler,
		},
		{
			MethodName: "VistesImport",
			Handler:    _WishlistAdmin_VistesImport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
